name: hoax-detection
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - asttokens==3.0.0
      - autopep8==2.3.2
      - black==25.1.0
      - cfgv==3.4.0
      - click==8.2.0
      - decorator==5.2.1
      - distlib==0.3.9
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.18.0
      - flake8==7.2.0
      - identify==2.6.10
      - ipython==8.36.0
      - jedi==0.19.2
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mypy-extensions==1.1.0
      - nbqa==1.9.1
      - nodeenv==1.9.1
      - packaging==25.0
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - pre-commit==4.2.0
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycodestyle==2.13.0
      - pyflakes==3.3.2
      - pygments==2.19.1
      - pyyaml==6.0.2
      - stack-data==0.6.3
      - tokenize-rt==6.1.0
      - tomli==2.2.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - virtualenv==20.31.2
      - wcwidth==0.2.13
      - requests==2.32.3
